### ISSUE TITLE
Allesfitter stops after cryptic error

### ISSUE THREAD

**Issue by jvines** [MNGuenther/allesfitter#21]
Hi,

I'm running allesfitter on a set of rvs and photometry, the rvs have a lot of noise from stellar activity which cannot be modeled with a single GP, so I'm trying my luck fitting 3 planets, thing is eventually, with both nested sampling and MCMC there comes a point where allesfitter says `function eanom failed to converge 6.2506241095242920       0.99989602064794081        1.7918474379209218E+069   8.6196351880484955E+068   9.2988391911607227E+068` and then apparently stops. Have you encountered this before? Is it actually crashing or should I be more patient?

Thank you!

**Comment by MNGuenther** [comment]
Hi @jvines this error comes from ellc (https://github.com/pmaxted/ellc). All Python errors are caught by try/except in allesfitter, but this one comes from ellc's underlying C code. It happens very rarely, but it can happen. The reason is always that you are sampling in non-physical areas of the parameter space, e.g. if a planet would lie within the star, and so on. If you email me your allesfit folder,

**Comment by jvines** [comment]
Okay then, I'll email you the params and settings files. Do you need anything else emailed??

**Comment by MNGuenther** [comment]
I would need the whole folder, including the data and your previous trials (logs/plots/save file etc). If the data is private, I can't do much (happy to sign an NDA and promise I won't steal it). Or you can send me a minimum example with simulated data that replicates the error (but that's probably not possible).

**Comment by jvines** [comment]
I see, I'll anonymize the private data then and send them your way. I suspect what might be the issue now that you mention unphysical areas, but maybe it's best you check it out :) Thank you!

**Comment by MNGuenther** [comment]
See also: https://github.com/MNGuenther/allesfitter/issues/18

**Comment by jvines** [comment]
Hi ! I found that it was the eccentricity after all. After commenting it out I no longer got the error.

I've got a new question, though. Is there an easy way to retrieve the logz of a model? I tried `allesfitter.ns_plot_bayes_factors` but I get this error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-96a90fa9d56d> in <module>
----> 1 allesfitter.ns_plot_bayes_factors(['../FITS/pato/Allesfit_final/'], return_logZ=True)

TypeError: ns_plot_bayes_factors() got an unexpected keyword argument 'return_logZ'
```

And I haven't found in the API a straightforward day to get it.

Cheers

**Comment by MNGuenther** [comment]
Hi @jvines, 

Glad to hear that and no worries -- 99% of all such issues are typos 👍 I already wrote a lot of typo-catching things into allesfitter. If you'd like to share what yours was, I can try to catch such typos in the future.

For future reference: Yes, ellc can crash with the "eanom" error if the eccentricity puts the planet's orbit through the star, which is unphsycial. To mitigate that, we include some simple pre-calculations in allesfitter, which skip ellc in such cases. Generally, you should be able to use eccentricity in your fits as long as you make sure your priors on it are physically reasonable. 

To get logZ:
`allesfitter.get_logZ(datadir)`

You can also automatically return it when making the comparison plots:
`allesfitter.ns_plot_bayes_factors(datadirs, return_logZ=True)`

**Comment by jvines** [comment]
Hi,

I've got another question: is this error `glimnega: error finding limit` fatal?? I just got it in a run that's 50 hours in and I don't want to terminate it just because of it...

**Comment by MNGuenther** [comment]
That is an ellc error (in their C code), so I think it's best to ask Pierre Maxted directly: https://github.com/pmaxted/ellc/search?q=%22glimnega%3A+error+finding+limit%22

With Python, we have no means of catching/excepting any of ellc's C errors. That would have to be caught directly in ellc's C code and then, e.g., return a NaN model light curve instead of raising an error.

The only thing one can do in Python/allesfitter is setting physically plausible priors so these ellc crashes don't happen (they mostly happen for colliding bodies).

Side note: 50h is a very long time, I think I've never seen any allesfit take that long. Feel free to email me your files and I can check how to speed it up. See also https://www.allesfitter.com/faq#h.p_8OVje-veCXVa

**Comment by jvines** [comment]
I think the main reason why it's running extremely slow is because I was using 1000 nlive in order to make sure to capture any modus in the posterior space properly, at least that's been my experience before, and I am using quite wide priors, which are known to slow down the nested sampling significantly. I'll send you the files for you to take a look at, I didn't see the very_sparse option so I'll use it now that the run finished..

Going back to the error from ellc, it turns out it wasn't fatal :P
