### ISSUE TITLE
Tutorial 02_transits - Exception has occurred: TypeError 

### ISSUE THREAD

**Issue by JosephKarpinski** [MNGuenther/allesfitter#41]
Python 3.8.5

Tutorial 02_transits - simulate_data.py  line 61 

See attached screen print
<img width="1443" alt="Screen Shot 2021-10-09 at 4 21 16 PM" src="https://user-images.githubusercontent.com/37123616/136672874-6789e006-8d8e-4882-abb4-14d9560e8271.png">
 below

**Comment by MNGuenther** [comment]
Thanks @JosephKarpinski! Don't worry about these simulate_data.py codes; they are just for us developers to make the examples. We have since changed the syntax of these functions, so the simulate_data.py  codes here are likely all outdated. We could update them in the future, but there is no actual usage for it. If you're indeed interested in using allesfitter to simulate your own data, I can give this a higher priority; just let me know.
